# Default values for helloworld.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 4
appdeployname: divya-deployment
appname: divyaworld

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
myimage:
  myfullreponame: ""
  #myfullreponame: ghcr.io/naveeng80/gitjenkinshelm:latest
  #reponame: "" -- ghcr.io/naveeng80/gitjenkinshelm
  #repotag: "" -- latest
  Whentopullimage: Always
  containerandtargetPort: 3000
  appcontainername: divya-container

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
myservice:
  type: LoadBalancer
  port: 80
  servicename: divya-service
  myprotocol: TCP

myscret:
  myreposecretname: github-divya-secret

dockerConfig:
  auths:
    "ghcr.io": 
       auth: "bmF2ZWVuZzgwOmdocF85c0JjN1RCeEJyRDVxZHkzZEFqbGVsVXhXMVM1azYyOVgzMmc="


#[Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes("naveeng80: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"))


